baseurl = "https://blog.benc.dev/"
languageCode = "en-us"
theme = "hello-friend"
paginate = 5

[params]
  contentTypeName = "blog"
  defaultTheme = "dark"
  showMenuItems = 4
  showReadingTime = false
  description = "Ben Coleman - blog / homepage / projects"
  images = ["thumb.png"]

[taxonomies]
  category = "categories"
  tag = "tags"
  minitag = "minitags"

[languages]
  [languages.en]
    title = "Pulse Code"
    subtitle = "Ben Coleman"

    [languages.en.params.logo]
      logoText = "pulse code"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
        weight = "30"
      [[languages.en.menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/blog"
        weight = "10"
      [[languages.en.menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects"
        weight = "20"   
      [[languages.en.menu.main]]
        identifier = "minis"
        name = "Minis"
        url = "/minis"
        weight = "70"
      [[languages.en.menu.main]]
        identifier = "personal"
        name = "Personal"
        url = "/personal"
        weight = "90"        