baseurl = "http://code.benco.io/personalsite/"
languageCode = "en-us"
theme = "hello-friend"
paginate = 5

[params]
  contentTypeName = "blog"
  defaultTheme = "dark"
  showMenuItems = 3
  showReadingTime = false

[languages]
  [languages.en]
    title = "Pulse Code"
    subtitle = "Ben Coleman"

    [languages.en.params.logo]
      logoText = "pulse code"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
        weight = "30"
      [[languages.en.menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/blog"
        weight = "10"
      [[languages.en.menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects"
        weight = "20"
      [[languages.en.menu.main]]
        identifier = "tags"
        name = "Blog Tags"
        url = "/tags"
        weight = "90"     
      [[languages.en.menu.main]]
        identifier = "personal"
        name = "Personal"
        url = "/personal"
        weight = "100"             